name: benbranyon-github-io
type: generic
docroot: _site
php_version: "8.1"
web_environment: []
router_http_port: "80"
router_https_port: "443"
xdebug_enabled: false
additional_hostnames: []
additional_fqdns: []
use_dns_when_possible: true
composer_version: ""
nodejs_version: "18"
